---
- name: Domain Join RHEL machines
  hosts: all
  become: true

  tasks:
  - name: Install packages
    ansible.builtin.dnf:
      name: 
        - samba-common-tools
        - realmd 
        - oddjob
        - oddjob-mkhomedir
        - sssd 
        - adcli 
        - krb5-workstation
      state: latest

  - name: Realm Discover
    ansible.builtin.shell:
      cmd: realm discover AAMU.EDU

  - name: Realm join
    ansible.builtin.shell: 
      cmd: echo GHCmd30nSIOnx! | realm join --user=ansiblesvc@AAMU.EDU AAMU.EDU

  - name: Edit sssd.conf
    ansible.builtin.shell:
      cmd: sed -i 's/use_fully_qualified_names = True/use_fully_qualified_names = False/' /etc/sssd/sssd.conf

  - name: Restart the sssd service
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: sssd