---
- name: Windows Server 2025 Activation
  hosts: all
  gather_facts: false
  become_method: runas
  tasks:
    - name: Run the Activation
      ansible.windows.win_shell: cscript slmgr.vbs /ipk B9PNQ-JD8TV-PJ9CB-T7966-8T4HQ
      args:
        chdir: C:\Windows\system32
      register: result
      ignore_errors: yes
      become: yes
      become_user: Administrator

    - name: Display Output
      debug:
        var: result.stdout_lines
